{% set name = "numba-mpi" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numba-mpi-{{ version }}.tar.gz
  sha256: 975d895e5a364cc02ca9951137825e3cf659ef2d34ce584ca85bf061de85c829

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0


requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - numpy
    - numba
    - mpi4py
    - python >=3.6

test:
  commands:
    - pip check
    - mpiexec python -c "import numba_mpi"
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-mpi/
  summary: Numba @njittable MPI wrappers tested on Linux, macOS and Windows
  dev_url: https://github.com/atmos-cloud-sim-uj/numba-mpi/
  doc_url: https://atmos-cloud-sim-uj.github.io/numba-mpi/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slayoo
