{% set name = "numba-mpi" %}
{% set version = "0.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8460af17ee64d34e51eb8cbd7d57d54ba9e32d85ed375e787e1f952423bd407c

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0


requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - numpy
    - numba
    - mpi4py
    - psutil
    - python >=3.6

test:
  commands:
    - pip check
    - mpiexec python -c "import numba_mpi"
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-mpi/
  summary: Numba @njittable MPI wrappers tested on Linux, macOS and Windows
  dev_url: https://github.com/numba-mpi/numba-mpi/
  doc_url: https://numba-mpi.github.io/numba-mpi/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slayoo
