{% set name = "numba-mpi" %}
{% set version = "0.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numba-mpi-{{ version }}.tar.gz
  sha256: 3c4d26f14a870b9a3e7d869a7b94ad18d14e8856ded68261024d528d8f244d27

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0


requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - numpy
    - numba
    - mpi4py
    - python >=3.6

test:
  commands:
    - pip check
    - mpiexec python -c "import numba_mpi"
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-mpi/
  summary: Numba @njittable MPI wrappers tested on Linux, macOS and Windows
  dev_url: https://github.com/numba-mpi/numba-mpi/
  doc_url: https://numba-mpi.github.io/numba-mpi/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slayoo
