{% set name = "numba-mpi" %}
{% set version = "1.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5b7b7c0cde9ea04fb6d0751e1f2106d248a2ca9dedc2721cefdea9ff8dc31bdc

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0


requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - numpy
    - numba
    - mpi4py
    - psutil
    - python >=3.6

test:
  commands:
    - pip check
    - mpiexec -n 1 python -c "import numba_mpi"
  requires:
    - pip

about:
  home: https://pypi.org/project/numba-mpi/
  summary: Numba @njittable MPI wrappers tested on Linux, macOS and Windows
  dev_url: https://github.com/numba-mpi/numba-mpi/
  doc_url: https://numba-mpi.github.io/numba-mpi/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slayoo
