{% set name = "numba-mpi" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 224ea629201879e725dfb3434a110106fc3e8994305dd4e6787661e5bcdc5b96

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 1


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - numpy
    - numba
    - mpi4py
    - psutil
    - python >={{ python_min }}

test:
  commands:
    - pip check
    - mpiexec -n 1 python -c "import numba_mpi"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/numba-mpi/
  summary: Numba @njittable MPI wrappers tested on Linux, macOS and Windows
  dev_url: https://github.com/numba-mpi/numba-mpi/
  doc_url: https://numba-mpi.github.io/numba-mpi/
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - slayoo
